# Generated by Django 4.2.4 on 2023-08-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_category_category_name_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
