# Generated by Django 4.2.4 on 2023-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='factory_quantity',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_remain_quantity',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_remain_quantity',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_send_quantity',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
