# Generated by Django 4.2.4 on 2023-08-25 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_factory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_add_main_quantity',
            field=models.IntegerField(default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='receive_main_quantity',
            field=models.IntegerField(default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory_quantity',
            field=models.IntegerField(default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_remain_quantity',
            field=models.IntegerField(default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_remain_quantity',
            field=models.IntegerField(default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_send_quantity',
            field=models.IntegerField(default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
