# Generated by Django 4.2.4 on 2023-08-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_shop_receive_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_categorys', to='main.category')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_codes', to='main.product')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_descriptions', to='main.product')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_price', to='main.product')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='main.product')),
                ('shop_receive_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_quantity_shop', to='main.product')),
                ('shop_remain_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remain_quantity_shop', to='main.product')),
                ('shop_send_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_quantity_shop', to='main.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products_status', to='main.product')),
            ],
        ),
    ]
