# Generated by Django 4.2.4 on 2023-08-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_shopproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='shop_receive_quantity',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='shop_remain_quantity',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='shop_send_quantity',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='status',
        ),
    ]
